---
- name: create a local repo for ambari
  hosts: localhost
  connection: local
    # Setting gather_facts: False on a playbook allows this implicit fact gathering to be skipped.
  gather_facts: False
  become: yes
  vars:
    local_repo_path: /var/www/html
  tasks:
    - name: confirm apache createrepo rsync installed
      yum: name={{item}} state=installed
      with_items:
         - httpd
         - createrepo
         - rsync
         - epel-release
         

    - name: Download ambari repos
      get_url:
        url: http://public-repo-1.hortonworks.com/ambari/centos7/2.x/updates/2.6.2.2/ambari.repo
        dest: /etc/yum.repos.d/ambari.repo

    - name: Download hdp repos
      get_url:
        url: http://public-repo-1.hortonworks.com/HDP/centos7/2.x/updates/2.6.3.0/hdp.repo
        dest: /etc/yum.repos.d/hdp.repo

    - name: create dirs for amabri and hdp repo
      file: path={{item}} owner=apache group=apache state=directory
      with_items:
         - "{{local_repo_path}}/ambari/centos7/2.x/updates/2.6.2.2"
         - "{{local_repo_path}}/HDP/centos7/2.x/updates/2.6.3.0"
         - "{{local_repo_path}}/HDP-UTILS-1.1.0.21/repos/centos7"


    # - name: create symlink
    #   file: src=/data/repo/centos/6.5/ dest=/data/repo/centos/6 state=link
    # - name: populate  repository
    #   command: '/usr/bin/rsync  -av --delete --delete-excluded --exclude "local*" --exclude "isos" --exclude "i386"  rsync://repos.dfw.quadranet.com/centos/6.5/ /data/repo/centos/6.5/'
    # - name: httpd.conf
    #   lineinfile:
    #       dest="/etc/httpd/conf/httpd.conf" regexp="^Alias /centos /data/repo/centos"
    #       insertafter="^DocumentRoot " line="Alias /centos /data/repo/centos"
    - name: restart wob server
      service: name=httpd state=restarted enabled=yes
