# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
# Vagrant multi-machine sample setup
# ref: https://stackoverflow.com/questions/24867252/allow-two-or-more-vagrant-vms-to-communicate-on-their-own-network

VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # dont generate a pub/private key for this connection
  # and use the unsecure private key shipped by vagrant by default
  # which resides under .vagrant.d/insecure_private_key
  # this way, the corresponding pub key will be inserted
  # by vagrant into  ~/.ssh/authorized_keys
  # https://github.com/hashicorp/vagrant/tree/master/keys
  config.ssh.insert_key = false
  # this is the default private_key used
  config.ssh.private_key_path = [ "~/.vagrant.d/insecure_private_key"]

  config.vm.define :hdpsandbox2 do |hdpsandbox2|
    # centos 7.5
    hdpsandbox2.vm.box = "bento/centos-7"
    hdpsandbox2.vm.box_version = "201808.24.0"
    hdpsandbox2.vm.network :private_network, ip: "10.0.0.23"
    hdpsandbox2.vm.network "forwarded_port", guest: 22, host: 2223
    hdpsandbox2.vm.network "forwarded_port", guest: 8080, host: 8083
    # for oozie UI
    hdpsandbox2.vm.network "forwarded_port", guest: 11000, host: 11003
    # for spark2 UI
    hdpsandbox2.vm.network "forwarded_port", guest: 18081, host: 18083
    hdpsandbox2.vm.hostname = "hdpsandbox2"
    hdpsandbox2.vm.provision "shell", path: "provision_machine.sh"

    hdpsandbox2.vm.provider :virtualbox do |vb|
      vb.name = "hdpsandbox2"
      vb.memory = 12384
      vb.cpus = 3
    end

  end

end
