- name:
  hosts: all
  # connection: local
    # Setting gather_facts: False on a playbook allows this implicit fact gathering to be skipped.
  gather_facts: False
  become: yes
  tasks:
    - name: install some packages
      yum:
        name:
          - nano
          - wget
          - unzip
        state: installed

- name: deploy MySQL and configure databases
  hosts: all
  become: yes

  roles:
   - db_mariadb

- name: deploy Apache, PHP and configure website code
  hosts: all
  become: yes

  roles:
    - web

- name: Download, deploy wordpress, connect it to its database
  hosts: all
  become: yes
    
  roles:
    - wordpress
