# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
# Vagrant multi-machine sample setup
# ref: https://stackoverflow.com/questions/24867252/allow-two-or-more-vagrant-vms-to-communicate-on-their-own-network

VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # dont generate a pub/private key for this connection
  # and use the unsecure private key shipped by vagrant by default
  # which resides under .vagrant.d/insecure_private_key
  # this way, the corresponding pub key will be inserted
  # by vagrant into  ~/.ssh/authorized_keys
  # https://github.com/hashicorp/vagrant/tree/master/keys
  config.ssh.insert_key = false
  # this is the default private_key used
  config.ssh.private_key_path = [ "~/.vagrant.d/insecure_private_key"]
  config.vm.synced_folder "C:\\Users\\ssa-pro\\Desktop\\work\\airflow", "/root/synced"
  # config.vm.synced_folder "C:\\Users\\ssa-pro\\Desktop\\work\\Project_airflow\\dags_dir", "/root/airflow/dags"

  config.vm.define :airflowDev do |airflowDev|
    # centos 7.5
    airflowDev.vm.box = "bento/centos-7"
    airflowDev.vm.box_version = "201808.24.0"
    airflowDev.vm.network :private_network, ip: "10.0.0.41"
    # Must specified `id: "ssh"` in order to override the default forwarded SSH port.
    #https://realguess.net/2015/10/06/overriding-the-default-forwarded-ssh-port-in-vagrant/
    airflowDev.vm.network "forwarded_port", guest: 22, host: 2241, id: "ssh"
    airflowDev.vm.network "forwarded_port", guest: 5678, host: 5678

    airflowDev.vm.hostname = "airflowDev"
    airflowDev.vm.provision "shell", path: "provision_machine.sh"
    airflowDev.vm.provider :virtualbox do |vb|
      vb.name = "airflowDev"
      vb.memory = 2048
      vb.cpus = 2
    end
  end

end
